# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\orderSystem.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_orderSystem(object):
    def setupUi(self, orderSystem):
        orderSystem.setObjectName("orderSystem")
        orderSystem.resize(600, 800)
        orderSystem.setMinimumSize(QtCore.QSize(600, 800))
        orderSystem.setMaximumSize(QtCore.QSize(600, 800))
        self.orderSystem_stackedWidget = QtWidgets.QStackedWidget(orderSystem)
        self.orderSystem_stackedWidget.setGeometry(QtCore.QRect(99, 19, 402, 762))
        self.orderSystem_stackedWidget.setObjectName("orderSystem_stackedWidget")
        self.nameInput_page = QtWidgets.QWidget()
        self.nameInput_page.setObjectName("nameInput_page")
        self.nameInput_widget = QtWidgets.QWidget(self.nameInput_page)
        self.nameInput_widget.setGeometry(QtCore.QRect(1, 355, 400, 50))
        self.nameInput_widget.setObjectName("nameInput_widget")
        self.nameInputTag_label = QtWidgets.QLabel(self.nameInput_widget)
        self.nameInputTag_label.setGeometry(QtCore.QRect(0, 0, 100, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.nameInputTag_label.setFont(font)
        self.nameInputTag_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nameInputTag_label.setObjectName("nameInputTag_label")
        self.nameInput_lineEdit = QtWidgets.QLineEdit(self.nameInput_widget)
        self.nameInput_lineEdit.setGeometry(QtCore.QRect(100, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.nameInput_lineEdit.setFont(font)
        self.nameInput_lineEdit.setObjectName("nameInput_lineEdit")
        self.nameInputConfirm_pushButton = QtWidgets.QPushButton(self.nameInput_page)
        self.nameInputConfirm_pushButton.setGeometry(QtCore.QRect(151, 500, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.nameInputConfirm_pushButton.setFont(font)
        self.nameInputConfirm_pushButton.setObjectName("nameInputConfirm_pushButton")
        self.orderSystem_stackedWidget.addWidget(self.nameInput_page)
        self.order_page = QtWidgets.QWidget()
        self.order_page.setObjectName("order_page")
        self.storeName_widget = QtWidgets.QWidget(self.order_page)
        self.storeName_widget.setGeometry(QtCore.QRect(1, 60, 400, 40))
        self.storeName_widget.setStyleSheet("")
        self.storeName_widget.setObjectName("storeName_widget")
        self.storeName_horizontalLayout = QtWidgets.QHBoxLayout(self.storeName_widget)
        self.storeName_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.storeName_horizontalLayout.setSpacing(0)
        self.storeName_horizontalLayout.setObjectName("storeName_horizontalLayout")
        self.storeName_label = QtWidgets.QLabel(self.storeName_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storeName_label.sizePolicy().hasHeightForWidth())
        self.storeName_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.storeName_label.setFont(font)
        self.storeName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.storeName_label.setObjectName("storeName_label")
        self.storeName_horizontalLayout.addWidget(self.storeName_label)
        self.storeName_horizontalLayout.setStretch(0, 7)
        self.itemTag_widget = QtWidgets.QWidget(self.order_page)
        self.itemTag_widget.setGeometry(QtCore.QRect(1, 100, 400, 30))
        self.itemTag_widget.setObjectName("itemTag_widget")
        self.itemTag_horizontalLayout = QtWidgets.QHBoxLayout(self.itemTag_widget)
        self.itemTag_horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.itemTag_horizontalLayout.setSpacing(5)
        self.itemTag_horizontalLayout.setObjectName("itemTag_horizontalLayout")
        self.itemNameTag_label = QtWidgets.QLabel(self.itemTag_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemNameTag_label.sizePolicy().hasHeightForWidth())
        self.itemNameTag_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.itemNameTag_label.setFont(font)
        self.itemNameTag_label.setAlignment(QtCore.Qt.AlignCenter)
        self.itemNameTag_label.setObjectName("itemNameTag_label")
        self.itemTag_horizontalLayout.addWidget(self.itemNameTag_label)
        self.priceTag_label = QtWidgets.QLabel(self.itemTag_widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.priceTag_label.setFont(font)
        self.priceTag_label.setStyleSheet("")
        self.priceTag_label.setAlignment(QtCore.Qt.AlignCenter)
        self.priceTag_label.setObjectName("priceTag_label")
        self.itemTag_horizontalLayout.addWidget(self.priceTag_label)
        self.amountTag_label = QtWidgets.QLabel(self.itemTag_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountTag_label.sizePolicy().hasHeightForWidth())
        self.amountTag_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.amountTag_label.setFont(font)
        self.amountTag_label.setObjectName("amountTag_label")
        self.itemTag_horizontalLayout.addWidget(self.amountTag_label)
        self.itemTag_horizontalLayout.setStretch(0, 7)
        self.itemTag_horizontalLayout.setStretch(1, 2)
        self.itemTag_horizontalLayout.setStretch(2, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.order_page)
        self.scrollArea.setGeometry(QtCore.QRect(0, 130, 402, 582))
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 580))
        self.scrollAreaWidgetContents.setToolTipDuration(-1)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.items_verticalLayout = QtWidgets.QVBoxLayout()
        self.items_verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.items_verticalLayout.setObjectName("items_verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.items_verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.items_verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.studentName_widget = QtWidgets.QWidget(self.order_page)
        self.studentName_widget.setGeometry(QtCore.QRect(1, 0, 400, 50))
        self.studentName_widget.setObjectName("studentName_widget")
        self.studentNameTag_label = QtWidgets.QLabel(self.studentName_widget)
        self.studentNameTag_label.setEnabled(True)
        self.studentNameTag_label.setGeometry(QtCore.QRect(0, 0, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.studentNameTag_label.setFont(font)
        self.studentNameTag_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.studentNameTag_label.setObjectName("studentNameTag_label")
        self.studentName_label = QtWidgets.QLabel(self.studentName_widget)
        self.studentName_label.setGeometry(QtCore.QRect(250, 0, 200, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.studentName_label.setFont(font)
        self.studentName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.studentName_label.setObjectName("studentName_label")
        self.orderConfirm_pushButton = QtWidgets.QPushButton(self.order_page)
        self.orderConfirm_pushButton.setGeometry(QtCore.QRect(151, 730, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.orderConfirm_pushButton.setFont(font)
        self.orderConfirm_pushButton.setObjectName("orderConfirm_pushButton")
        self.orderSystem_stackedWidget.addWidget(self.order_page)

        self.retranslateUi(orderSystem)
        self.orderSystem_stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(orderSystem)

    def retranslateUi(self, orderSystem):
        _translate = QtCore.QCoreApplication.translate
        orderSystem.setWindowTitle(_translate("orderSystem", "Order"))
        self.nameInputTag_label.setText(_translate("orderSystem", "姓名"))
        self.nameInput_lineEdit.setText(_translate("orderSystem", "輸入姓名"))
        self.nameInputConfirm_pushButton.setText(_translate("orderSystem", "下一步"))
        self.storeName_label.setText(_translate("orderSystem", "店名"))
        self.itemNameTag_label.setText(_translate("orderSystem", "品項"))
        self.priceTag_label.setText(_translate("orderSystem", "價格"))
        self.amountTag_label.setText(_translate("orderSystem", "數量"))
        self.studentNameTag_label.setText(_translate("orderSystem", "<html><head/><body><p><span style=\" font-size:20pt;\">姓名</span></p></body></html>"))
        self.studentName_label.setText(_translate("orderSystem", "王小明"))
        self.orderConfirm_pushButton.setText(_translate("orderSystem", "送出"))
