# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\AccountPage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountPage(object):
    def setupUi(self, AccountPage):
        AccountPage.setObjectName("AccountPage")
        AccountPage.resize(1298, 763)
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountPage)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.read_radioButton = QtWidgets.QRadioButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.read_radioButton.setFont(font)
        self.read_radioButton.setChecked(True)
        self.read_radioButton.setObjectName("read_radioButton")
        self.horizontalLayout_3.addWidget(self.read_radioButton)
        self.write_radioButton = QtWidgets.QRadioButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.write_radioButton.setFont(font)
        self.write_radioButton.setObjectName("write_radioButton")
        self.horizontalLayout_3.addWidget(self.write_radioButton)
        self.selectTable_comboBox = QtWidgets.QComboBox(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.selectTable_comboBox.setFont(font)
        self.selectTable_comboBox.setEditable(False)
        self.selectTable_comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.selectTable_comboBox.setObjectName("selectTable_comboBox")
        self.selectTable_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.selectTable_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 5)
        self.horizontalLayout_3.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.SaveTable_pushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.SaveTable_pushButton.setFont(font)
        self.SaveTable_pushButton.setObjectName("SaveTable_pushButton")
        self.horizontalLayout_2.addWidget(self.SaveTable_pushButton)
        self.OutputTable_pushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.OutputTable_pushButton.setFont(font)
        self.OutputTable_pushButton.setObjectName("OutputTable_pushButton")
        self.horizontalLayout_2.addWidget(self.OutputTable_pushButton)
        self.horizontalLayout_2.setStretch(0, 14)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.showTable = QtWidgets.QTableView(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.showTable.setFont(font)
        self.showTable.setObjectName("showTable")
        self.verticalLayout.addWidget(self.showTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.insertRow_PushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.insertRow_PushButton.setFont(font)
        self.insertRow_PushButton.setObjectName("insertRow_PushButton")
        self.horizontalLayout.addWidget(self.insertRow_PushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.deleteRow_PushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.deleteRow_PushButton.setFont(font)
        self.deleteRow_PushButton.setObjectName("deleteRow_PushButton")
        self.horizontalLayout.addWidget(self.deleteRow_PushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AccountPage)
        QtCore.QMetaObject.connectSlotsByName(AccountPage)

    def retranslateUi(self, AccountPage):
        _translate = QtCore.QCoreApplication.translate
        AccountPage.setWindowTitle(_translate("AccountPage", "Form"))
        self.read_radioButton.setText(_translate("AccountPage", "查看"))
        self.write_radioButton.setText(_translate("AccountPage", "填寫"))
        self.selectTable_comboBox.setItemText(0, _translate("AccountPage", "基本資料"))
        self.SaveTable_pushButton.setText(_translate("AccountPage", "儲存表格"))
        self.OutputTable_pushButton.setText(_translate("AccountPage", "輸出表格"))
        self.insertRow_PushButton.setText(_translate("AccountPage", "新增"))
        self.deleteRow_PushButton.setText(_translate("AccountPage", "刪除"))
