# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\AccountPage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountPage(object):
    def setupUi(self, AccountPage):
        AccountPage.setObjectName("AccountPage")
        AccountPage.resize(1266, 827)
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountPage)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.read_radioButton = QtWidgets.QRadioButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.read_radioButton.setFont(font)
        self.read_radioButton.setChecked(True)
        self.read_radioButton.setObjectName("read_radioButton")
        self.horizontalLayout_3.addWidget(self.read_radioButton)
        self.write_radioButton = QtWidgets.QRadioButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.write_radioButton.setFont(font)
        self.write_radioButton.setObjectName("write_radioButton")
        self.horizontalLayout_3.addWidget(self.write_radioButton)
        self.selectTable_comboBox = QtWidgets.QComboBox(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.selectTable_comboBox.setFont(font)
        self.selectTable_comboBox.setEditable(False)
        self.selectTable_comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.selectTable_comboBox.setObjectName("selectTable_comboBox")
        self.selectTable_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.selectTable_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 5)
        self.horizontalLayout_3.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.Condition_Layout = QtWidgets.QHBoxLayout()
        self.Condition_Layout.setObjectName("Condition_Layout")
        self.label = QtWidgets.QLabel(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Condition_Layout.addWidget(self.label)
        self.columnCondition_comboBox = QtWidgets.QComboBox(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.columnCondition_comboBox.setFont(font)
        self.columnCondition_comboBox.setObjectName("columnCondition_comboBox")
        self.columnCondition_comboBox.addItem("")
        self.Condition_Layout.addWidget(self.columnCondition_comboBox)
        self.contentCondition_comboBox = QtWidgets.QComboBox(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.contentCondition_comboBox.setFont(font)
        self.contentCondition_comboBox.setObjectName("contentCondition_comboBox")
        self.contentCondition_comboBox.addItem("")
        self.Condition_Layout.addWidget(self.contentCondition_comboBox)
        self.addConditionpushButton = QtWidgets.QPushButton(AccountPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addConditionpushButton.sizePolicy().hasHeightForWidth())
        self.addConditionpushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.addConditionpushButton.setFont(font)
        self.addConditionpushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.addConditionpushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addConditionpushButton.setIconSize(QtCore.QSize(20, 20))
        self.addConditionpushButton.setAutoDefault(False)
        self.addConditionpushButton.setDefault(False)
        self.addConditionpushButton.setFlat(False)
        self.addConditionpushButton.setObjectName("addConditionpushButton")
        self.Condition_Layout.addWidget(self.addConditionpushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Condition_Layout.addItem(spacerItem1)
        self.Condition_Layout.setStretch(0, 3)
        self.Condition_Layout.setStretch(1, 5)
        self.Condition_Layout.setStretch(2, 5)
        self.Condition_Layout.setStretch(3, 1)
        self.Condition_Layout.setStretch(4, 7)
        self.verticalLayout.addLayout(self.Condition_Layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.SaveTable_pushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.SaveTable_pushButton.setFont(font)
        self.SaveTable_pushButton.setObjectName("SaveTable_pushButton")
        self.horizontalLayout_2.addWidget(self.SaveTable_pushButton)
        self.RefreshTable_pushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.RefreshTable_pushButton.setFont(font)
        self.RefreshTable_pushButton.setObjectName("RefreshTable_pushButton")
        self.horizontalLayout_2.addWidget(self.RefreshTable_pushButton)
        self.horizontalLayout_2.setStretch(0, 14)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.showTable = QtWidgets.QTableView(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.showTable.setFont(font)
        self.showTable.setObjectName("showTable")
        self.verticalLayout.addWidget(self.showTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.insertRow_PushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.insertRow_PushButton.setFont(font)
        self.insertRow_PushButton.setObjectName("insertRow_PushButton")
        self.horizontalLayout.addWidget(self.insertRow_PushButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.deleteRow_PushButton = QtWidgets.QPushButton(AccountPage)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.deleteRow_PushButton.setFont(font)
        self.deleteRow_PushButton.setObjectName("deleteRow_PushButton")
        self.horizontalLayout.addWidget(self.deleteRow_PushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AccountPage)
        QtCore.QMetaObject.connectSlotsByName(AccountPage)

    def retranslateUi(self, AccountPage):
        _translate = QtCore.QCoreApplication.translate
        AccountPage.setWindowTitle(_translate("AccountPage", "Form"))
        self.read_radioButton.setText(_translate("AccountPage", "查看"))
        self.write_radioButton.setText(_translate("AccountPage", "填寫"))
        self.selectTable_comboBox.setItemText(0, _translate("AccountPage", "基本資料"))
        self.label.setText(_translate("AccountPage", "篩選條件："))
        self.columnCondition_comboBox.setItemText(0, _translate("AccountPage", "無"))
        self.contentCondition_comboBox.setItemText(0, _translate("AccountPage", "無"))
        self.addConditionpushButton.setText(_translate("AccountPage", "+"))
        self.SaveTable_pushButton.setText(_translate("AccountPage", "儲存表格"))
        self.RefreshTable_pushButton.setText(_translate("AccountPage", "重新整理"))
        self.insertRow_PushButton.setText(_translate("AccountPage", "新增"))
        self.deleteRow_PushButton.setText(_translate("AccountPage", "刪除"))
