# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\checkTodayOrder.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TodayRecord(object):
    def setupUi(self, TodayRecord):
        TodayRecord.setObjectName("TodayRecord")
        TodayRecord.resize(600, 800)
        TodayRecord.setMinimumSize(QtCore.QSize(600, 800))
        TodayRecord.setMaximumSize(QtCore.QSize(600, 800))
        self.label = QtWidgets.QLabel(TodayRecord)
        self.label.setGeometry(QtCore.QRect(0, 25, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(TodayRecord)
        self.scrollArea.setGeometry(QtCore.QRect(50, 230, 500, 450))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 448))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.storeName_label = QtWidgets.QLabel(TodayRecord)
        self.storeName_label.setGeometry(QtCore.QRect(0, 75, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.storeName_label.setFont(font)
        self.storeName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.storeName_label.setObjectName("storeName_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(TodayRecord)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 190, 501, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout.setStretch(0, 12)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 4)
        self.totalPrice_label = QtWidgets.QLabel(TodayRecord)
        self.totalPrice_label.setGeometry(QtCore.QRect(400, 680, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.totalPrice_label.setFont(font)
        self.totalPrice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPrice_label.setObjectName("totalPrice_label")
        self.Cancel_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Cancel_pushButton.setGeometry(QtCore.QRect(430, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Cancel_pushButton.setFont(font)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.Confirm_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Confirm_pushButton.setGeometry(QtCore.QRect(240, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Confirm_pushButton.setFont(font)
        self.Confirm_pushButton.setObjectName("Confirm_pushButton")
        self.totalPeople_label = QtWidgets.QLabel(TodayRecord)
        self.totalPeople_label.setGeometry(QtCore.QRect(50, 680, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.totalPeople_label.setFont(font)
        self.totalPeople_label.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPeople_label.setObjectName("totalPeople_label")
        self.Refresh_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Refresh_pushButton.setGeometry(QtCore.QRect(450, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Refresh_pushButton.setFont(font)
        self.Refresh_pushButton.setStyleSheet("")
        self.Refresh_pushButton.setObjectName("Refresh_pushButton")
        self.ReturnHomePage_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.ReturnHomePage_pushButton.setGeometry(QtCore.QRect(50, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.ReturnHomePage_pushButton.setFont(font)
        self.ReturnHomePage_pushButton.setStyleSheet("")
        self.ReturnHomePage_pushButton.setObjectName("ReturnHomePage_pushButton")
        self.menuDate_label = QtWidgets.QLabel(TodayRecord)
        self.menuDate_label.setGeometry(QtCore.QRect(0, 125, 600, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.menuDate_label.setFont(font)
        self.menuDate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menuDate_label.setObjectName("menuDate_label")

        self.retranslateUi(TodayRecord)
        QtCore.QMetaObject.connectSlotsByName(TodayRecord)

    def retranslateUi(self, TodayRecord):
        _translate = QtCore.QCoreApplication.translate
        TodayRecord.setWindowTitle(_translate("TodayRecord", "Form"))
        self.label.setText(_translate("TodayRecord", "今日訂單"))
        self.storeName_label.setText(_translate("TodayRecord", "店名"))
        self.label_4.setText(_translate("TodayRecord", "品項"))
        self.label_3.setText(_translate("TodayRecord", "單價"))
        self.label_5.setText(_translate("TodayRecord", "數量"))
        self.label_6.setText(_translate("TodayRecord", "總價"))
        self.totalPrice_label.setText(_translate("TodayRecord", "總額"))
        self.Cancel_pushButton.setText(_translate("TodayRecord", "刪除訂單"))
        self.Confirm_pushButton.setText(_translate("TodayRecord", "完成訂單"))
        self.totalPeople_label.setText(_translate("TodayRecord", "人數"))
        self.Refresh_pushButton.setText(_translate("TodayRecord", "重新整理"))
        self.ReturnHomePage_pushButton.setText(_translate("TodayRecord", "返回主選單"))
        self.menuDate_label.setText(_translate("TodayRecord", "TextLabel"))
