# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\checkTodayOrder.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TodayRecord(object):
    def setupUi(self, TodayRecord):
        TodayRecord.setObjectName("TodayRecord")
        TodayRecord.resize(600, 800)
        TodayRecord.setMinimumSize(QtCore.QSize(600, 800))
        TodayRecord.setMaximumSize(QtCore.QSize(600, 800))
        self.label = QtWidgets.QLabel(TodayRecord)
        self.label.setGeometry(QtCore.QRect(0, 25, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.storeName_label = QtWidgets.QLabel(TodayRecord)
        self.storeName_label.setGeometry(QtCore.QRect(0, 75, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.storeName_label.setFont(font)
        self.storeName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.storeName_label.setObjectName("storeName_label")
        self.totalPrice_label = QtWidgets.QLabel(TodayRecord)
        self.totalPrice_label.setGeometry(QtCore.QRect(400, 680, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.totalPrice_label.setFont(font)
        self.totalPrice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPrice_label.setObjectName("totalPrice_label")
        self.Cancel_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Cancel_pushButton.setGeometry(QtCore.QRect(430, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Cancel_pushButton.setFont(font)
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.Confirm_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Confirm_pushButton.setGeometry(QtCore.QRect(240, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Confirm_pushButton.setFont(font)
        self.Confirm_pushButton.setObjectName("Confirm_pushButton")
        self.totalPeople_label = QtWidgets.QLabel(TodayRecord)
        self.totalPeople_label.setGeometry(QtCore.QRect(50, 680, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.totalPeople_label.setFont(font)
        self.totalPeople_label.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPeople_label.setObjectName("totalPeople_label")
        self.Refresh_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.Refresh_pushButton.setGeometry(QtCore.QRect(450, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.Refresh_pushButton.setFont(font)
        self.Refresh_pushButton.setStyleSheet("")
        self.Refresh_pushButton.setObjectName("Refresh_pushButton")
        self.ReturnHomePage_pushButton = QtWidgets.QPushButton(TodayRecord)
        self.ReturnHomePage_pushButton.setGeometry(QtCore.QRect(50, 740, 120, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.ReturnHomePage_pushButton.setFont(font)
        self.ReturnHomePage_pushButton.setStyleSheet("")
        self.ReturnHomePage_pushButton.setObjectName("ReturnHomePage_pushButton")
        self.menuDate_label = QtWidgets.QLabel(TodayRecord)
        self.menuDate_label.setGeometry(QtCore.QRect(0, 125, 600, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.menuDate_label.setFont(font)
        self.menuDate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menuDate_label.setObjectName("menuDate_label")
        self.todayOrder_stackedWidget = QtWidgets.QStackedWidget(TodayRecord)
        self.todayOrder_stackedWidget.setGeometry(QtCore.QRect(50, 190, 500, 490))
        self.todayOrder_stackedWidget.setObjectName("todayOrder_stackedWidget")
        self.todayOrder_page = QtWidgets.QWidget()
        self.todayOrder_page.setObjectName("todayOrder_page")
        self.todayOrder_scrollArea = QtWidgets.QScrollArea(self.todayOrder_page)
        self.todayOrder_scrollArea.setGeometry(QtCore.QRect(0, 40, 500, 450))
        self.todayOrder_scrollArea.setWidgetResizable(True)
        self.todayOrder_scrollArea.setObjectName("todayOrder_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 448))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.todayOrderDetail_pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.todayOrderDetail_pushButton.setFont(font)
        self.todayOrderDetail_pushButton.setObjectName("todayOrderDetail_pushButton")
        self.verticalLayout.addWidget(self.todayOrderDetail_pushButton)
        self.todayOrder_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.todayOrderTag_widget = QtWidgets.QWidget(self.todayOrder_page)
        self.todayOrderTag_widget.setGeometry(QtCore.QRect(0, 0, 500, 42))
        self.todayOrderTag_widget.setObjectName("todayOrderTag_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.todayOrderTag_widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.todayOrderTag_widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_7 = QtWidgets.QLabel(self.todayOrderTag_widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.todayOrderTag_widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.todayOrderTag_widget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_2.setStretch(0, 12)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 4)
        self.todayOrder_stackedWidget.addWidget(self.todayOrder_page)
        self.todayOrderDetail_page = QtWidgets.QWidget()
        self.todayOrderDetail_page.setObjectName("todayOrderDetail_page")
        self.todayOrderDetail_widget = QtWidgets.QWidget(self.todayOrderDetail_page)
        self.todayOrderDetail_widget.setGeometry(QtCore.QRect(0, 0, 500, 490))
        self.todayOrderDetail_widget.setObjectName("todayOrderDetail_widget")
        self.todayOrder_stackedWidget.addWidget(self.todayOrderDetail_page)

        self.retranslateUi(TodayRecord)
        self.todayOrder_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TodayRecord)

    def retranslateUi(self, TodayRecord):
        _translate = QtCore.QCoreApplication.translate
        TodayRecord.setWindowTitle(_translate("TodayRecord", "Form"))
        self.label.setText(_translate("TodayRecord", "今日訂單"))
        self.storeName_label.setText(_translate("TodayRecord", "店名"))
        self.totalPrice_label.setText(_translate("TodayRecord", "總額"))
        self.Cancel_pushButton.setText(_translate("TodayRecord", "刪除訂單"))
        self.Confirm_pushButton.setText(_translate("TodayRecord", "完成訂單"))
        self.totalPeople_label.setText(_translate("TodayRecord", "人數"))
        self.Refresh_pushButton.setText(_translate("TodayRecord", "重新整理"))
        self.ReturnHomePage_pushButton.setText(_translate("TodayRecord", "返回主選單"))
        self.menuDate_label.setText(_translate("TodayRecord", "TextLabel"))
        self.todayOrderDetail_pushButton.setText(_translate("TodayRecord", "詳細內容"))
        self.label_2.setText(_translate("TodayRecord", "品項"))
        self.label_7.setText(_translate("TodayRecord", "單價"))
        self.label_8.setText(_translate("TodayRecord", "數量"))
        self.label_9.setText(_translate("TodayRecord", "總價"))
