# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\setPage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setPage(object):
    def setupUi(self, setPage):
        setPage.setObjectName("setPage")
        setPage.setEnabled(True)
        setPage.resize(1300, 800)
        self.setPage_stackedWidget = QtWidgets.QStackedWidget(setPage)
        self.setPage_stackedWidget.setGeometry(QtCore.QRect(0, 0, 600, 800))
        self.setPage_stackedWidget.setObjectName("setPage_stackedWidget")
        self.setDate_page = QtWidgets.QWidget()
        self.setDate_page.setObjectName("setDate_page")
        self.date_dateEdit = QtWidgets.QDateEdit(self.setDate_page)
        self.date_dateEdit.setGeometry(QtCore.QRect(150, 375, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.date_dateEdit.setFont(font)
        self.date_dateEdit.setCalendarPopup(True)
        self.date_dateEdit.setObjectName("date_dateEdit")
        self.dateTag_label = QtWidgets.QLabel(self.setDate_page)
        self.dateTag_label.setGeometry(QtCore.QRect(125, 300, 350, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.dateTag_label.setFont(font)
        self.dateTag_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTag_label.setObjectName("dateTag_label")
        self.setDate_nextStep_pushButton = QtWidgets.QPushButton(self.setDate_page)
        self.setDate_nextStep_pushButton.setGeometry(QtCore.QRect(235, 480, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.setDate_nextStep_pushButton.setFont(font)
        self.setDate_nextStep_pushButton.setObjectName("setDate_nextStep_pushButton")
        self.label = QtWidgets.QLabel(self.setDate_page)
        self.label.setGeometry(QtCore.QRect(0, 25, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.setPage_stackedWidget.addWidget(self.setDate_page)
        self.setMenu_page = QtWidgets.QWidget()
        self.setMenu_page.setObjectName("setMenu_page")
        self.add_fav_PushButton = QtWidgets.QPushButton(self.setMenu_page)
        self.add_fav_PushButton.setGeometry(QtCore.QRect(50, 725, 150, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.add_fav_PushButton.setFont(font)
        self.add_fav_PushButton.setObjectName("add_fav_PushButton")
        self.confirm_Button = QtWidgets.QPushButton(self.setMenu_page)
        self.confirm_Button.setGeometry(QtCore.QRect(250, 725, 100, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.confirm_Button.setFont(font)
        self.confirm_Button.setObjectName("confirm_Button")
        self.fav_confirm_Button = QtWidgets.QPushButton(self.setMenu_page)
        self.fav_confirm_Button.setEnabled(False)
        self.fav_confirm_Button.setGeometry(QtCore.QRect(400, 90, 100, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.fav_confirm_Button.setFont(font)
        self.fav_confirm_Button.setObjectName("fav_confirm_Button")
        self.favoStore_comboBox = QtWidgets.QComboBox(self.setMenu_page)
        self.favoStore_comboBox.setGeometry(QtCore.QRect(100, 90, 270, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.favoStore_comboBox.setFont(font)
        self.favoStore_comboBox.setEditable(False)
        self.favoStore_comboBox.setCurrentText("")
        self.favoStore_comboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.favoStore_comboBox.setObjectName("favoStore_comboBox")
        self.option_input_area = QtWidgets.QScrollArea(self.setMenu_page)
        self.option_input_area.setGeometry(QtCore.QRect(50, 165, 502, 517))
        self.option_input_area.setWidgetResizable(True)
        self.option_input_area.setObjectName("option_input_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 515))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.option_input_area.setWidget(self.scrollAreaWidgetContents)
        self.scroll_navigater = QtWidgets.QWidget(self.setMenu_page)
        self.scroll_navigater.setGeometry(QtCore.QRect(50, 135, 500, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_navigater.sizePolicy().hasHeightForWidth())
        self.scroll_navigater.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.scroll_navigater.setFont(font)
        self.scroll_navigater.setObjectName("scroll_navigater")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scroll_navigater)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.option_name_label_2 = QtWidgets.QLabel(self.scroll_navigater)
        self.option_name_label_2.setObjectName("option_name_label_2")
        self.horizontalLayout_2.addWidget(self.option_name_label_2)
        self.price_label_2 = QtWidgets.QLabel(self.scroll_navigater)
        self.price_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.price_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.price_label_2.setObjectName("price_label_2")
        self.horizontalLayout_2.addWidget(self.price_label_2)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 3)
        self.store_name_label = QtWidgets.QLabel(self.setMenu_page)
        self.store_name_label.setGeometry(QtCore.QRect(100, 20, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(20)
        self.store_name_label.setFont(font)
        self.store_name_label.setObjectName("store_name_label")
        self.store_name_lineEdit = QtWidgets.QLineEdit(self.setMenu_page)
        self.store_name_lineEdit.setGeometry(QtCore.QRect(200, 20, 300, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.store_name_lineEdit.setFont(font)
        self.store_name_lineEdit.setObjectName("store_name_lineEdit")
        self.returnSetDate_pushButton = QtWidgets.QPushButton(self.setMenu_page)
        self.returnSetDate_pushButton.setGeometry(QtCore.QRect(400, 725, 150, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.returnSetDate_pushButton.setFont(font)
        self.returnSetDate_pushButton.setObjectName("returnSetDate_pushButton")
        self.setPage_stackedWidget.addWidget(self.setMenu_page)
        self.menuDetail_page = QtWidgets.QWidget()
        self.menuDetail_page.setObjectName("menuDetail_page")
        self.menuDetailStoreName_label = QtWidgets.QLabel(self.menuDetail_page)
        self.menuDetailStoreName_label.setGeometry(QtCore.QRect(0, 25, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.menuDetailStoreName_label.setFont(font)
        self.menuDetailStoreName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menuDetailStoreName_label.setObjectName("menuDetailStoreName_label")
        self.menuDetail_widget = QtWidgets.QWidget(self.menuDetail_page)
        self.menuDetail_widget.setGeometry(QtCore.QRect(50, 135, 500, 545))
        self.menuDetail_widget.setObjectName("menuDetail_widget")
        self.menuDetail_verticalLayout = QtWidgets.QVBoxLayout(self.menuDetail_widget)
        self.menuDetail_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.menuDetail_verticalLayout.setSpacing(0)
        self.menuDetail_verticalLayout.setObjectName("menuDetail_verticalLayout")
        self.menuDetailDate_label = QtWidgets.QLabel(self.menuDetail_page)
        self.menuDetailDate_label.setGeometry(QtCore.QRect(0, 75, 600, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.menuDetailDate_label.setFont(font)
        self.menuDetailDate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menuDetailDate_label.setObjectName("menuDetailDate_label")
        self.returnSetDate_pushButton_2 = QtWidgets.QPushButton(self.menuDetail_page)
        self.returnSetDate_pushButton_2.setGeometry(QtCore.QRect(400, 725, 150, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.returnSetDate_pushButton_2.setFont(font)
        self.returnSetDate_pushButton_2.setObjectName("returnSetDate_pushButton_2")
        self.modifyMenuDetail_pushButton = QtWidgets.QPushButton(self.menuDetail_page)
        self.modifyMenuDetail_pushButton.setGeometry(QtCore.QRect(250, 725, 100, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.modifyMenuDetail_pushButton.setFont(font)
        self.modifyMenuDetail_pushButton.setObjectName("modifyMenuDetail_pushButton")
        self.add_fav_PushButton_2 = QtWidgets.QPushButton(self.menuDetail_page)
        self.add_fav_PushButton_2.setGeometry(QtCore.QRect(50, 725, 150, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.add_fav_PushButton_2.setFont(font)
        self.add_fav_PushButton_2.setObjectName("add_fav_PushButton_2")
        self.setPage_stackedWidget.addWidget(self.menuDetail_page)
        self.label_2 = QtWidgets.QLabel(setPage)
        self.label_2.setGeometry(QtCore.QRect(600, 25, 700, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.returnHomePage_pushButton = QtWidgets.QPushButton(setPage)
        self.returnHomePage_pushButton.setGeometry(QtCore.QRect(1100, 725, 150, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.returnHomePage_pushButton.setFont(font)
        self.returnHomePage_pushButton.setObjectName("returnHomePage_pushButton")
        self.menuManage_widget = QtWidgets.QWidget(setPage)
        self.menuManage_widget.setGeometry(QtCore.QRect(600, 75, 600, 50))
        self.menuManage_widget.setObjectName("menuManage_widget")
        self.menuManageYear_dateEdit = QtWidgets.QDateEdit(self.menuManage_widget)
        self.menuManageYear_dateEdit.setGeometry(QtCore.QRect(50, 5, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.menuManageYear_dateEdit.setFont(font)
        self.menuManageYear_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 12, 28), QtCore.QTime(0, 0, 0)))
        self.menuManageYear_dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2022, 9, 11), QtCore.QTime(0, 0, 0)))
        self.menuManageYear_dateEdit.setCalendarPopup(False)
        self.menuManageYear_dateEdit.setObjectName("menuManageYear_dateEdit")
        self.menuRecord_widget = QtWidgets.QWidget(setPage)
        self.menuRecord_widget.setGeometry(QtCore.QRect(650, 135, 600, 545))
        self.menuRecord_widget.setObjectName("menuRecord_widget")
        self.menuRecord_verticalLayout = QtWidgets.QVBoxLayout(self.menuRecord_widget)
        self.menuRecord_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.menuRecord_verticalLayout.setSpacing(0)
        self.menuRecord_verticalLayout.setObjectName("menuRecord_verticalLayout")
        self.deleteMenuRecord_pushButton = QtWidgets.QPushButton(setPage)
        self.deleteMenuRecord_pushButton.setGeometry(QtCore.QRect(950, 725, 100, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.deleteMenuRecord_pushButton.setFont(font)
        self.deleteMenuRecord_pushButton.setObjectName("deleteMenuRecord_pushButton")
        self.showMenuDetail_pushButton = QtWidgets.QPushButton(setPage)
        self.showMenuDetail_pushButton.setGeometry(QtCore.QRect(800, 725, 100, 35))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.showMenuDetail_pushButton.setFont(font)
        self.showMenuDetail_pushButton.setObjectName("showMenuDetail_pushButton")

        self.retranslateUi(setPage)
        self.setPage_stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(setPage)

    def retranslateUi(self, setPage):
        _translate = QtCore.QCoreApplication.translate
        setPage.setWindowTitle(_translate("setPage", "Form"))
        self.date_dateEdit.setDisplayFormat(_translate("setPage", "yyyy/M/d"))
        self.dateTag_label.setText(_translate("setPage", "請設定此菜單之日期"))
        self.setDate_nextStep_pushButton.setText(_translate("setPage", "下一步"))
        self.label.setText(_translate("setPage", "設定菜單"))
        self.add_fav_PushButton.setText(_translate("setPage", "加到常用菜單"))
        self.confirm_Button.setText(_translate("setPage", "確認"))
        self.fav_confirm_Button.setText(_translate("setPage", "確認"))
        self.option_name_label_2.setText(_translate("setPage", "品項"))
        self.price_label_2.setText(_translate("setPage", "價格"))
        self.store_name_label.setText(_translate("setPage", "店名"))
        self.returnSetDate_pushButton.setText(_translate("setPage", "返回設定日期"))
        self.menuDetailStoreName_label.setText(_translate("setPage", "菜單內容"))
        self.menuDetailDate_label.setText(_translate("setPage", "日期"))
        self.returnSetDate_pushButton_2.setText(_translate("setPage", "返回設定日期"))
        self.modifyMenuDetail_pushButton.setText(_translate("setPage", "修改"))
        self.add_fav_PushButton_2.setText(_translate("setPage", "加到常用菜單"))
        self.label_2.setText(_translate("setPage", "管理菜單"))
        self.returnHomePage_pushButton.setText(_translate("setPage", "返回主選單"))
        self.menuManageYear_dateEdit.setDisplayFormat(_translate("setPage", "yyyy"))
        self.deleteMenuRecord_pushButton.setText(_translate("setPage", "刪除"))
        self.showMenuDetail_pushButton.setText(_translate("setPage", "內容"))
